navikt/arbeidsrettet-dialog

src/App.less
src/view/Dialog.less
src/view/Dialog.tsx
src/view/HenvendelseList.tsx
src/view/henvendelseList.less

Rette også noen feil i layout detaljer (borders kun nederst, tastefeil i app_body og henvendelse-list)

FO-2348: Flytte Undefined sjekk inn i HenvendelseList, Rette layout.

---

src/App.less
src/view/Dialog.less
src/view/dialognew.less
src/view/dialogoverview.less
src/view/dialogpreview.less

Responsivt flytende design. Oppgave der jeg satt med Linn og bestemte størrelse på kolonner på ulike skjermstrørrelser.

FO-2408: Småfiks av design

---

src/App.less
src/App.tsx
src/mock/dialog.ts
src/view/DialogBanner.less
src/view/DialogBanner.tsx
src/view/DialogOverview.tsx
src/view/DialogOverviewHeader.tsx

Fikserier-PR ga bug med hvit stripe i bunnen av appen som gjorde at appen ristet. Fikset her.
I tillegg har jeg skjult banner i mobil-dialogvisning og fjernet viktig meldinger-checkboxen.

Fikserierfiks

---

src/view/dialogoverview.less

byttet bare overflow-y fra scroll til auto

FO-2419: Scrollbar skal ikke vises hvis det ikke er mange nok dialoger

---

src/mock/aktivitet.ts
src/mock/arena.tsx
src/mock/dialog.ts
src/mock/index.ts
src/utils/date.ts
src/utils/typer.ts
src/view/Aktivitetskort.tsx
src/view/AktivitetskortInfoBox.tsx
src/view/AktivitetskortPreview.tsx
src/view/HenvendelseList.tsx

- Retter typer på aktivitet
- Legger til type for arenaaktivitet
- Setter opp enums for aktivitetstyper
- Forenkler oppsettet i mapping til infoboksen i aktivitetsvisning

FO-2511: Setter opp typer for aktivitet og arenaaktivitet

---

src/view/dialog/Dialog.less
src/view/dialog/DialogHeader.module.less
src/view/dialog/DialogHeader.tsx

Fikser bug og konverterer til css modules

FO-2541: Fikser så header ikke vises på middels skjerm når dialog ikke er tilknyttet aktivitet

---

package-lock.json
package.json
public/index.html
src/index.tsx
src/mock/index.ts

for å kunne rendre i veilarbpersonflatefs

[KAIZEN-0] leger til støtte for nav-spa

---

src/mock/Dialog.ts
src/view/dialog/Dialog.tsx
src/view/dialog/HistoriskInfo.module.less
src/view/dialog/HistoriskInfo.tsx

fjerner muligheten til å sende henvendelser på historisek dialoger

[FO-2650] Infomelding på historiske dialoger

---

src/view/banner/AppBanner.tsx

Hvis bruker har åpen en dialog

FO-2417: Skjul dialogbanner på mobil visning

---

src/view/Provider.tsx
src/view/aktivitet/AktivitetskortLinke.tsx
src/view/aktivitet/AktivitetskortPreview.tsx

da det er mulig at aktivitesplan ikke har mountet
som fører til at den ikke endrer urlen

[KAIZEN-0] endrer til å sette urlen i arbeidsretet-dialog også

---

src/view/banner/AppBanner.less
src/view/dialogliste/NyDialogLink.module.less
src/view/dialogliste/NyDialogLink.tsx

baner ikon plassering
ny dialog knapp for veileder fiks

smaffiks styling

---

src/utils/UpdateEvent.tsx
src/view/App.tsx
src/view/dialog/Dialog.tsx
src/view/dialog/DialogInputBox.tsx
src/view/dialog/NyDialogForm.tsx
src/view/statusAdvarsel/Manuell.tsx

for og oppdatere dialog/aktivitet/oppfolging

[FO-2721] produsere og lytte for uppdate event

---

decorator.yaml

[KAIZEN-0] leger til basepath på api og redirekt

---

src/view/dialog/Dialog.module.less
src/view/dialog/NyDialog.tsx
src/view/info/InfoOmDialogSide.module.less
src/view/info/InfoOmDialogSide.tsx

Noen sider skal ha scroll på overflow. Legg til regel som overstyrer
ved behov

KAIZEN-0: Fiks overflow auto

---

src/api/dialog.ts
src/mock/Dialog.ts
src/view/dialog/DialogInputBox.tsx
src/view/dialog/NyDialogForm.tsx
src/view/dialogliste/etiketer/Etikett.tsx

https://jira.adeo.no/browse/FO-2719

FO-2719: Venter på svar fra

---

public/index.html
src/mock/demo/DemoBanner.tsx
src/mock/demo/DemoDashboard.less
src/mock/demo/DemoDashboard.tsx
src/mock/demo/sessionstorage.ts
src/view/App.module.less

Lettere å teste lokalt hvordan det vil se ut

Mock hodefot

---

src/view/dialog/DialogInputBox.tsx
src/view/henvendelse/HenvendelseList.tsx
src/view/henvendelse/useScrollToLastHenvendelse.tsx

Alltid scroll ved nye henvendelser

---

src/utils/Typer.ts
src/view/dialogliste/EtikettListe.tsx

for gjeldendeEskaleringsvarsel

[FO-2923] bugfiks feil datatype paa tilhorendeDialogId 

---

src/view/dialog/Dialog.tsx

Som en veileder som har en dialogtråd åpen og går til aktivitetsplan
Ønsker jeg at dialogen ikke skal bli lest når jeg står inne på aktivitetsplan
Slik at jeg ikke mister at det er kommet en ny dialog

FO-2982: Bare les dialog hvis bruker ser på den

---

src/view/AktivitetProvider.tsx
src/view/dialog/DialogHeader.module.less
src/view/dialog/DialogHeader.tsx
src/view/dialog/DialogOverskrift.tsx
src/view/dialog/HeaderInnhold.tsx
src/view/dialog/IngenDialog.tsx
src/view/dialog/NyDialog.tsx
src/view/dialog/TilbakeKnapp.module.less
src/view/dialog/TilbakeKnapp.tsx
src/view/dialog/TittelHeader.tsx
src/view/info/InfoOmDialogSide.tsx
src/view/utils/utils.ts

Fikser trellokort: https://trello.com/c/q9BYFmHg/50-sm%C3%A5fiks-dialog-felt-hopper
Og rydder litt:
- Det var mange komponenter i DialogHeader, disse er flyttet ut i egne filer
- Tilbakeknapp kode var kopiert flere steder, trekker isteden ut og bruker begge stedene

Småfiks og rydde litt

---

src/felleskomponenter/textArea/TextArea.module.less
src/felleskomponenter/textArea/TextArea.tsx
src/view/dialog/NyDialogForm.module.less
src/view/dialog/NyDialogForm.tsx

https://trello.com/c/Vhj0azyN/99-sm%C3%A5fiks-dialog-visuelt-mobil

Småfiks på mobil for ny dialog + småting på desktop

---

src/felleskomponenter/textArea/TextArea.module.less
src/view/dialog/NyDialogForm.tsx
src/view/dialog/dialogInput/HendvendelseInput.module.less
src/view/lest/LestTidspunkt.module.less

https://trello.com/c/fu87M3CV/168-sm%C3%A5fiks-dialog-klar-til-utvikling

Småfiks og stillekkasje

---

.github/workflows/build.yml
package-lock.json
package.json
src/test/Oppfolging.test.tsx
src/view/dialog/NyDialogForm.tsx
src/view/dialog/SkrivMeldingInput.tsx
src/view/dialog/TemaInput.tsx
src/view/dialog/dialogInput/DialogInputBox.tsx
src/view/dialog/dialogInput/HendvendelseInput.tsx
tsconfig.json

https://trello.com/c/FOrxVJXA/120-oppdatere-react-scripts-i-dialogen
Har også fikset noen TS-feil for å kunne kjøre prosjektet etter bumpingen.

Bumpe react-scripts til 4.0.2

---

src/mock/Dialog.ts
src/mock/SistOppdatert.ts
src/mock/index.ts
src/utils/Typer.ts
src/view/DialogProvider.tsx

https://trello.com/c/0x4WbZb7/159-dialog-for-eksternbruker-fungerer-ikke-lenger-%C3%A5-motta-melding-uten-%C3%A5-refreshe

Fikser surr med datoformat som gjør at sistOppdatert ikke oppdateres

---

src/utils/Date.test.ts
src/utils/Date.ts

viser nå riktig varighet

---

src/mock/Aktivitet.ts
src/mock/Dialog.ts
src/utils/aktivitetTypes.ts
src/view/aktivitet/AktivitetskortInfoBox.tsx
src/view/aktivitet/AktivitetskortPreview.tsx
src/view/aktivitet/StillingFraNavAktivitet.tsx
src/view/aktivitet/TextUtils.tsx
src/view/aktivitet/etiketter/StillingFraNavEtikett.tsx
src/view/aktivitet/etiketter/sokestatusEtikett.module.less

* Støtte for stilling fra nav, med enkel rendring

Prodsetting Stilling fra Nav (#350)

---

nais-dev-ekstern-gcp.yaml
nais-dev-intern-gcp.yaml
nais-prod-ekstern-gcp.yaml
nais-prod-intern-gcp.yaml

TODO dra inn nytt pto-frontend image

Ny loginservice config fra configmap

---

.github/workflows/deploy-feature-branch.yml
src/felleskomponenter/timeoutmodal/TimeoutModal.tsx
src/felleskomponenter/timeoutmodal/Timeoutmodal.less

Virker ikke helt, fordi loginservice ikke støtter returnUrl med path parametre, men vi blir kvitt alarmene

Reload ved timeout

---

src/felleskomponenter/timeoutmodal/TimeoutModal.tsx
src/view/App.tsx
src/view/aktivitet/AktivitetskortLinke.tsx
src/view/utils/utils.ts

dette må også fikses i aktivitetsplan

Fiks intern flate context path

---

package.json

Tror denne skal fikse alle PRene fra dependabot

Oppdaterer react-scripts

---

src/view/melding/MeldingList.tsx

fiks scroll i internflate ved utsending av dialogmelding

---

src/view/aktivitet/Aktivitetskort.tsx
src/view/aktivitet/AktivitetskortInfoBox.module.less
src/view/aktivitet/DialogMedAktivitetHeader.tsx
src/view/dialog/Dialog.tsx
src/view/dialog/DialogHeader.module.less
src/view/dialog/DialogInfoMelding.tsx
src/view/dialog/HistoriskInfo.tsx
src/view/dialog/NyDialogForm.tsx
src/view/dialogliste/DialogOversikt.tsx
src/view/info/DialogIkkeValgt.tsx
src/view/melding/Meldinger.tsx
tailwind.config.js

- Max w screens
- Move Aktivitet link also
- min w 320 dialogliste
- Start ny dialog tweaks

Better big-screens scaling

---

.github/workflows/gh-pages.yml

fix gh pages

---

src/api/useFetchHarNivaa4.ts
src/view/Provider.tsx

- Better error messages
- Send fnr

better error messages

---

src/api/nyDialogWs.ts
src/view/Provider.tsx
src/view/dialogProvider/dialogStore.ts

Only receive events that is actually subscribed to from PLEASE instead of all events

Subscribe to events

---

src/api/UseApiBasePath.ts
src/mock/handlers.ts
src/view/OppfolgingProvider.tsx

Dataene er like men endepuntet er nytt og bruker POST for å unngå fnr i url

Bruk POST endepunkt for å hente oppfolgingsdata

---

schema.graphqls
src/api/UseApiBasePath.ts
src/mock/handlers.ts
src/utils/Typer.ts
src/view/DialogProvider.tsx
src/view/dialogProvider/dialogGraphql.ts
src/view/dialogProvider/dialogStore.ts

- **Bruk POST på sistOppdatert**
- **Bruk graphql endepunkt til å hente dialoger**
- **Bruk lest endepunkt uten fnr i query**
- **Opprett dialog uten fnr i query**
- **Ferdig behandlet uten fnr i query**
- **Venter på svar uten fnr i url**
- **Fix graphql mocking**

uten fnr i url
